name: 'ChatOps For Pull Requests'
description: Listen for special comments, or chatops commands in the comments of a PR.
author: Hamel Husain
inputs:
  APP_PEM:
    description: string version of your PEM file used to authenticate as a GitHub App
    required: false
  APP_ID:
    description: you GITHUB App ID.
    required: false
  TRIGGER_PHRASE:
    description: this is the phrase in a PR comment that you want to trigger downstream Actions.  Example - "/deploy-app-test"
    required: true
  INDICATOR_LABEL:
    description: label that will be added to the PR if a triggering comment is detected.  This is used to trigger downstream Actions with the right context of the PR.
    required: false
    default: ""
  TEST_EVENT_PATH:
    description: An alternate place to fetch the payload for testing and debugging when making changes to this Action.  This is set to they system environment variable $GITHUB_EVENT_PATH by default.
    require: false
    default: ""
outputs:
  TRAILING_LINE:
    description: the text that immediately follows the triggering phrase that is on the same line.  For example,  "/trigger-phrase foo bar\n next line" will emit the value "foo bar" This is intended to be used as arguments for downstream actions.
  TRAILING_TOKEN:
    description: this is the next token that immediately follows the triggering phrase that is on the same line.  For example,  "/trigger-phrase foo bar" will emit the value "foo". This is intended to be used as arguments for downstream actions.
  BOOL_TRIGGERED:
    description: true or false depending on if the trigger phrase was detected and this is a pull request.
  PULL_REQUEST_NUMBER:
    description: the number of the pull request
  COMMENTER_USERNAME:
    description: The GitHub username of the person that made the triggering comment in the PR.
  BRANCH_NAME:
    description: The name of the branch corresponding to the PR.
  SHA:
    description: The SHA of the branch on the PR at the time the triggering comment was made.
  APP_INSTALLATION_TOKEN:
    description: The installation access token for the GitHub App corresponding to and the current repository.  This is only retrieved if the `APP_PEM` and `APP_ID` inputs are supplied.
branding:
  color: 'gray-dark'
  icon: 'message-square'
runs:
  using: 'docker'
  image: 'docker://hamelsmu/chatops'
